version: "3.8"

services:
  app:
    build:
      context: "./"
      dockerfile: "./docker/fastapi/Dockerfile"
      args:
        image_type: "debug"
    image: "brbcoffee/subs"
    ports:
      - "80:80"
      - "5678:5678"
      - "3000:3000"
    volumes:
      - "./subtitles:/app/subtitles:cached"
      - "./frontend:/app/frontend"
