version: "3.8"

services:
  app:
    build:
      context: "./"
      dockerfile: "./docker/fastapi/Dockerfile"
      args:
        image_type: "debug"
    ports:
      - "80:80"
      - "5678:5678"
    volumes:
      - "./skam:/app/skam:cached"
      - "./frontend:/app/frontend"
