version: "3.8"

services:
  app:
    build:
      context: "./"
      dockerfile: "./docker/fastapi/Dockerfile"
    image: "ghcr.io/bjornsnoen/nrk-subtitles"
    ports:
      - "80:80"
      - "5678:5678"
      - "3000:3000"
