version: "3.8"

services:
  app:
    build:
      context: "./"
      dockerfile: "./docker/fastapi/Dockerfile"
      args:
        supervisorconf: "supervisord.debug.conf"
    ports:
      - "80:80"
      - "5678:5678"
    volumes:
      - "./skam:/app/skam:cached"
    environment:
      - "DEBUG=1"
      - "DEBUG_LISTEN_HOST=0.0.0.0"
      - "DEBUG_LISTEN_PORT=5678"